title: The Silmarillion
author: Jasper Gilley
email: cruxcapacitorcontact@gmail.com
description: >-
  J.R.R. Tolkien's _The Silmarillion_, illustrated by Stable Diffusion. A project by Jasper Gilley.

social:
  twitter: 0xjasper
  github: jagilley

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
